-- Sample payment data for testing
INSERT INTO payments (
  patient_id, 
  appointment_id, 
  amount_cents, 
  payment_method, 
  payment_date, 
  procedure_name, 
  description, 
  status, 
  insurance_covered_cents, 
  patient_responsibility_cents
) VALUES 
-- Sample patient payments (using a test patient ID)
('43819944', 
 'fb2764e4-05be-436b-9798-535f320d10b1', 
 25000, 
 'credit_card', 
 '2024-12-15 10:30:00', 
 'Routine Cleaning', 
 'Regular checkup and cleaning', 
 'completed', 
 15000, 
 10000),

('43819944', 
 NULL, 
 45000, 
 'insurance', 
 '2024-11-20 14:15:00', 
 'Dental Filling', 
 'Cavity filling - upper left molar', 
 'completed', 
 35000, 
 10000),

('43819944', 
 NULL, 
 120000, 
 'credit_card', 
 '2024-10-05 09:45:00', 
 'Root Canal Treatment', 
 'Root canal therapy - tooth #19', 
 'completed', 
 80000, 
 40000),

('43819944', 
 NULL, 
 30000, 
 'cash', 
 '2024-09-12 16:20:00', 
 'Dental X-Ray', 
 'Full mouth X-rays for treatment planning', 
 'completed', 
 25000, 
 5000),

('43819944', 
 NULL, 
 75000, 
 'check', 
 '2024-08-08 11:00:00', 
 'Crown Placement', 
 'Porcelain crown - tooth #14', 
 'completed', 
 50000, 
 25000);

-- Sample forms data for testing
INSERT INTO forms (
  title, 
  description, 
  file_name, 
  file_url, 
  category, 
  display_order
) VALUES 
('Patient Medical History Form', 
 'Complete medical and dental history questionnaire required before your first visit', 
 'medical-history-form.pdf', 
 'https://example.com/forms/medical-history-form.pdf', 
 'pre-appointment', 
 1),

('Insurance Information Form', 
 'Provide your current insurance details and coverage information', 
 'insurance-info-form.pdf', 
 'https://example.com/forms/insurance-info-form.pdf', 
 'insurance', 
 2),

('Post-Treatment Care Instructions', 
 'Important care instructions to follow after your dental procedure', 
 'post-care-instructions.pdf', 
 'https://example.com/forms/post-care-instructions.pdf', 
 'post-treatment', 
 1),

('Emergency Contact Form', 
 'Emergency contact information and consent forms', 
 'emergency-contact-form.pdf', 
 'https://example.com/forms/emergency-contact-form.pdf', 
 'general', 
 3);